
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zxgsqsdhnwbldytzvwsq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp4Z3Nxc2RobndibGR5dHp2d3NxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMxNzg1NTQsImV4cCI6MjA1ODc1NDU1NH0.6SQIrNpkbOUu-_tqUeCC_CP99eJpl_mItnDpUiCPJ3M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
